# Generated by Django 5.0 on 2024-02-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(verbose_name='Nazwa galerii')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'M.01 - Galerie',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gallery.gallerymodel', verbose_name='Galeria')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'M.02 - Zdjęcia',
                'ordering': ['add_date'],
            },
        ),
    ]
