# Generated by Django 5.0 on 2023-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeunit',
            name='id_order',
            field=models.IntegerField(null=True, unique=True, verbose_name='Kolejność'),
        ),
    ]
