# Generated by Django 5.0 on 2023-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_typeunit_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
