# Generated by Django 5.0 on 2023-12-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_county_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeunit',
            options={'ordering': ['id'], 'verbose_name': 'Rodzaj jednostki', 'verbose_name_plural': 'Rodzaje jednostek'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
