# Generated by Django 5.0 on 2024-02-23 17:16

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0004_alter_typeunit_options_alter_unit_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_acceptance', models.DateField(blank=True, null=True, verbose_name='Data programu')),
                ('no_acceptance_document', models.CharField(blank=True, max_length=15, null=True, verbose_name='L.dz. dokumentu')),
                ('scan_program', models.FileField(blank=True, null=True, upload_to=project.models.upload_scan, verbose_name='Program inwestycji')),
                ('project_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nazwa zadania')),
                ('investment_cost_estimate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='WKI')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Informacje')),
                ('date_of_settlement', models.DateField(blank=True, null=True, verbose_name='Data rozliczenia')),
                ('scan_settlement', models.FileField(blank=True, null=True, upload_to=project.models.upload_scan, verbose_name='Rozliczenie')),
                ('realized', models.BooleanField(default=False, verbose_name='Zrealizowane')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='unit.unit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Inwestycyja',
                'verbose_name_plural': 'M.02 - Inwestycje',
                'ordering': ['date_of_acceptance'],
            },
        ),
        migrations.CreateModel(
            name='ContractorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nazwa')),
                ('nip', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NIP')),
                ('address', models.CharField(max_length=30, null=True, verbose_name='Adres')),
                ('zip_code', models.CharField(max_length=6, null=True, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='Miasto')),
                ('information', models.TextField(blank=True, default='', null=True, verbose_name='Informacje')),
                ('slug', models.SlugField(unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'M.01 - Kontrahenci',
                'ordering': ['name'],
                'unique_together': {('nip',)},
            },
        ),
    ]
