# Generated by Django 5.0 on 2024-01-23 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('unit', '0004_alter_typeunit_options_alter_unit_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Priorytet')),
            ],
            options={
                'verbose_name': 'Priorytet',
                'verbose_name_plural': 'M.08 - Priorytety',
            },
        ),
        migrations.AlterModelOptions(
            name='financesource',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'M.07 - Konta'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'M.04 - Grupy'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Paragraf i pozycja', 'verbose_name_plural': 'M.05 - Paragrafy i pozycje'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section'], 'verbose_name': 'Rozdział', 'verbose_name_plural': 'M.03 - Rozdziały'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Źródło finansowania', 'verbose_name_plural': 'M.06 - Źródła finansowania'},
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.IntegerField(unique=True, verbose_name='Grupa'),
        ),
        migrations.CreateModel(
            name='ItemPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Nazwa zadania')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Szacowany koszt')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Utworzenie')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPlan', to='plan.financesource', verbose_name='Źródło finansowania')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.unit', verbose_name='Jednostka')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPlan', to='plan.prioritymodel', verbose_name='Priorytet')),
            ],
            options={
                'verbose_name': 'Zadanie w planie',
                'verbose_name_plural': 'M.02 - Zadania w planie',
                'ordering': ['create'],
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('date', models.DateField(verbose_name='Data')),
                ('tasks_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Utworzenie')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='plan.itemplanmodel', verbose_name='Zadania')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'M.01 - Plany',
                'ordering': ['date'],
            },
        ),
    ]
