# Generated by Django 5.0 on 2024-01-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_prioritymodel_alter_financesource_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='itemplanmodel',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemPlan', to='plan.planmodel', verbose_name='Plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Podtytuł'),
        ),
    ]
