# Generated by Django 5.0 on 2024-02-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_planmodel_item_itemplanmodel_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Podtytuł'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='tasks_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Suma'),
        ),
    ]
