# Generated by Django 5.0 on 2024-02-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_planmodel_subtitle_alter_planmodel_tasks_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='subtitle',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Podtytuł'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='tasks_cost',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='Suma'),
        ),
    ]
